### ISSUE TITLE
Update PeerDependencies to allow react-async 0.9.0

### ISSUE THREAD

**Issue by tjmehta** [andreypopp/react-quickstart#10]
$ npm install --save react-router-component
   ...
npm ERR! peerinvalid The package react-async does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-router-component@0.18.1 wants react-async@~0.8.0

npm ERR! System Darwin 13.1.0
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save" "react-router-component"
npm ERR! cwd /Users/tjmehta/Developer/+github/harbormaster
npm ERR! node -v v0.11.10
npm ERR! npm -v 1.3.22
npm ERR! code EPEERINVALID
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/tjmehta/Developer/+github/harbormaster/npm-debug.log
npm ERR! not ok code 0

**Comment by andreypopp** [comment]
That's strange because `react-router-component` depends on `react-async@0.8.0`. Did you install `react-async` separately before?

**Comment by tjmehta** [comment]
Yup, I actually jumped the gun and assumed it would work. Will it not?

Tejesh

**Comment by andreypopp** [comment]
@tjmehta just downgrade react-async in your app to 0.8.0 cause react-router-component isn't compatible with 0.9.0 yet.

**Comment by tjmehta** [comment]
Thanks

On Tuesday, April 8, 2014, Andrey Popp notifications@github.com wrote:

> @tjmehta https://github.com/tjmehta just downgrade react-async in your
> app to 0.8.0 cause react-router-component isn't compatible with 0.9.0 yet.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/andreypopp/react-quickstart/issues/10#issuecomment-39819746
> .

## 

Typed using my thumbs..

**Comment by matthewconstantine** [comment]
Ran into this same issue but required a different fix. Looks like react-router-component 0.18.2 requires react-async 0.9.0 but 0.18.0 doesn't. Worked after I specified `"react-router-component": "0.18.0"` explicitly without the tilde.

**Comment by andreypopp** [comment]
Fixed.
